In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)

In [3]:
covid = pd.read_csv('../capstone-data/covid-restrictions.csv')
cta = pd.read_csv('../capstone-data/cta-monthly-primary.csv')
auto = pd.read_excel('../capstone-data/agg_auto.xlsx')
crashes = pd.read_csv('../capstone-data/crash_fin.csv')

# Prep CTA

In [3]:
cta.dtypes

month_beginning              object
avg_weekday_rides           float64
avg_saturday_rides          float64
avg_sunday-holiday_rides    float64
monthtotal                  float64
dtype: object

In [4]:
cta.rename(columns={'month_beginning':'date'},inplace=True)

In [5]:
cta['date']=pd.to_datetime(cta['date'])

In [6]:
cta.dtypes

date                        datetime64[ns]
avg_weekday_rides                  float64
avg_saturday_rides                 float64
avg_sunday-holiday_rides           float64
monthtotal                         float64
dtype: object

In [7]:
cta.set_index('date',inplace=True)
cta.sort_index(inplace=True)

# Prep Auto

In [8]:
auto.rename(columns={'Unnamed: 0':'date'},inplace=True)

In [9]:
auto.drop(columns={'Unnamed: 4'},inplace=True)

In [10]:
auto.dtypes

date                   datetime64[ns]
new_light_truck_reg           float64
new_car_reg                   float64
new_total_reg                 float64
dtype: object

In [11]:
auto.set_index('date',inplace=True)
auto.sort_index(inplace=True)

In [4]:
auto

    Unnamed: 0  new_light_truck_reg  new_car_reg  new_total_reg Unnamed: 4
0   2006-01-01              13166.0      13961.0        27127.0        NaN
1   2006-02-01              11239.5      12597.0        23836.5        NaN
2   2006-03-01              11716.5      13620.5        25337.0        NaN
3   2006-04-01              11716.5      13620.5        25337.0        NaN
4   2006-05-01              11177.5      14052.5        25230.0        NaN
5   2006-06-01              12249.0      16954.5        29203.5        NaN
6   2006-07-01              12249.0      16954.5        29203.5        NaN
7   2006-08-01                  NaN          NaN            NaN        NaN
8   2006-09-01              11585.5      15831.0        27416.5        NaN
9   2006-10-01              11585.5      15831.0        27416.5        NaN
10  2006-11-01                  NaN          NaN            NaN        NaN
11  2006-12-01              11046.5      12598.0        23644.5        NaN
12  2007-01-01              10219.0      11063.0        21282.0        NaN
13  2007-02-01              10219.0      11063.0        21282.0        NaN
14  2007-03-01              10787.0      11883.0        22670.0        NaN
15  2007-04-01              10787.0      11883.0        22670.0        NaN
16  2007-05-01              10689.5      12633.0        23322.5        NaN
17  2007-06-01              11607.5      16397.5        28005.0        NaN
18  2007-07-01              11607.5      16397.5        28005.0        NaN
19  2007-08-01                  NaN          NaN            NaN        NaN
20  2007-09-01              13400.5      16208.0        29608.5        NaN
21  2007-10-01              13400.5      16208.0        29608.5        NaN
22  2007-11-01                  NaN          NaN            NaN        NaN
23  2007-12-01                  NaN          NaN            NaN        NaN
24  2008-01-01                  NaN          NaN            NaN        NaN
25  2008-02-01                  NaN          NaN            NaN        NaN
26  2008-03-01              10612.0      12564.5        23176.5        NaN
27  2008-04-01              10612.0      12564.5        23176.5        NaN
28  2008-05-01                  NaN          NaN            NaN        NaN
29  2008-06-01                  NaN          NaN            NaN        NaN
30  2008-07-01                  NaN          NaN            NaN        NaN
31  2008-08-01                  NaN          NaN            NaN        NaN
32  2008-09-01              11037.0      13358.5        24395.5        NaN
33  2008-10-01              11037.0      13358.5        24395.5        NaN
34  2008-11-01                  NaN          NaN            NaN        NaN
35  2008-12-01                  NaN          NaN            NaN        NaN
36  2009-01-01                  NaN          NaN            NaN        NaN
37  2009-02-01                  NaN          NaN            NaN        NaN
38  2009-03-01                  NaN          NaN            NaN        NaN
39  2009-04-01                  NaN          NaN            NaN        NaN
40  2009-05-01                  NaN          NaN            NaN        NaN
41  2009-06-01                  NaN          NaN            NaN        NaN
42  2009-07-01                  NaN          NaN        21544.0        NaN
43  2009-08-01                  NaN          NaN        22583.0        NaN
44  2009-09-01              10502.0      18113.0        28615.0        NaN
45  2009-10-01               8903.0      10851.0        19754.0        NaN
46  2009-11-01                  NaN          NaN            NaN        NaN
47  2009-12-01              10465.0      10294.0        20759.0        NaN
48  2010-01-01               9611.0       9656.0        19267.0        NaN
49  2010-02-01                  NaN          NaN            NaN        NaN
50  2010-03-01              10049.0      10582.0        20631.0        NaN
51  2010-04-01               9479.0      10676.0        20155.0        NaN
52  2010-05-01               9509.0      11107.0        20616.0        NaN
53  2010-06-01               9273.0      11007.0        20280.0        NaN
54  2010-07-01              11409.0      13328.0        24737.0        NaN
55  2010-08-01              10814.0      12490.0        23304.0        NaN
56  2010-09-01              13011.0      15035.0        28046.0        NaN
57  2010-10-01               7507.0       8417.0        15924.0        NaN
58  2010-11-01               9901.0      10434.0        20335.0        NaN
59  2010-12-01              12295.0      12451.0        24746.0        NaN
60  2011-01-01              12481.0      11664.0        24145.0        NaN
61  2011-02-01               8106.0       7758.0        15864.0        NaN
62  2011-03-01              12954.0      13820.0        26774.0        NaN
63  2011-04-01              11086.0      13450.0        24536.0        NaN
64  2011-05-01              10131.0      12597.0        22728.0        NaN
65  2011-06-01              13556.0      16350.0        29906.0        NaN
66  2011-07-01              13624.0      16282.0        29906.0        NaN
67  2011-08-01              10769.0      11689.0        22458.0        NaN
68  2011-09-01              15273.0      15924.0        31197.0        NaN
69  2011-10-01              11007.0      11267.0        22274.0        NaN
70  2011-11-01              10213.0      10058.0        20271.0        NaN
71  2011-12-01              14244.0      13507.0        27751.0        NaN
72  2012-01-01              11674.0      11212.0        22886.0        NaN
73  2012-02-01               8949.0       8737.0        17686.0        NaN
74  2012-03-01              11968.0      13654.0        25622.0        NaN
75  2012-04-01              11158.0      14322.0        25480.0        NaN
76  2012-05-01              11535.0      15101.0        26636.0        NaN
77  2012-06-01              15192.0      17745.0        32937.0        NaN
78  2012-07-01              11992.0      14027.0        26019.0        NaN
79  2012-08-01              11508.0      13801.0        25309.0        NaN
80  2012-09-01              15463.0      18217.0        33680.0        NaN
81  2012-10-01              11790.0      13094.0        24884.0        NaN
82  2012-11-01              10172.0      10937.0        21109.0        NaN
83  2012-12-01              14293.0      14480.0        28773.0        NaN
84  2013-01-01              10168.0      11418.0        21586.0        NaN
85  2013-02-01              11040.0      11846.0        22886.0        NaN
86  2013-03-01              12829.0      14945.0        27774.0        NaN
87  2013-04-01              13753.0      16516.0        30269.0        NaN
88  2013-05-01              15273.0      18229.0        33502.0        NaN
89  2013-06-01              13565.0      16371.0        29936.0        NaN
90  2013-07-01              15193.0      17779.0        32972.0        NaN
91  2013-08-01              14537.0      16826.0        31363.0        NaN
92  2013-09-01              13987.0      15641.0        29628.0        NaN
93  2013-10-01              12269.0      13722.0        25991.0        NaN
94  2013-11-01              13050.0      13701.0        26751.0        NaN
95  2013-12-01              14899.0      14375.0        29274.0        NaN
96  2014-01-01              11430.0       9812.0        21242.0        NaN
97  2014-02-01              13165.0      11482.0        24647.0        NaN
98  2014-03-01              17150.0      16870.0        34020.0        NaN
99  2014-04-01              16049.0      16365.0        32414.0        NaN
100 2014-05-01              17379.0      18038.0        35417.0        NaN
101 2014-06-01              16330.0      16979.0        33309.0        NaN
102 2014-07-01              17137.0      17108.0        34245.0        NaN
103 2014-08-01              17922.0      18011.0        35933.0        NaN
104 2014-09-01              17343.0      15571.0        32914.0        NaN
105 2014-10-01              14748.0      13439.0        28187.0        NaN
106 2014-11-01              16520.0      14003.0        30523.0
107 2014-12-01              17318.0      14426.0        31744.0        NaN
108 2015-01-01              13356.0      10705.0        24061.0        NaN
109 2015-02-01              13368.0      10101.0        23469.0        NaN
110 2015-03-01              20092.0      16612.0        36704.0        NaN
111 2015-04-01              17210.0      14305.0        31515.0        NaN
112 2015-05-01              19569.0      16435.0        36004.0        NaN
113 2015-06-01              18713.0      15264.0        33977.0        NaN
114 2015-07-01              19885.0      15597.0        35482.0        NaN
115 2015-08-01              21506.0      17485.0        38991.0        NaN
116 2015-09-01              19109.0      14131.0        33240.0        NaN
117 2015-10-01              17855.0      12965.0        30820.0        NaN
118 2015-11-01              19161.0      12443.0        31604.0        NaN
119 2015-12-01              19335.0      11853.0        31188.0        NaN
120 2016-01-01              15222.0      10231.0        25453.0        NaN
121 2016-02-01              16876.0      11626.0        28502.0        NaN
122 2016-03-01              18460.0      13093.0        31553.0        NaN
123 2016-04-01              18209.0      12599.0        30808.0        NaN
124 2016-05-01              20544.0      14196.0        34740.0        NaN
125 2016-06-01              18635.0      13553.0        32188.0        NaN
126 2016-07-01              21043.0      14044.0        35087.0        NaN
127 2016-08-01              21542.0      14747.0        36289.0        NaN
128 2016-09-01              19787.0      12842.0        32629.0        NaN
129 2016-10-01              19516.0      12054.0        31570.0        NaN
130 2016-11-01              19298.0      11057.0        30355.0        NaN
131 2016-12-01              21677.0      11874.0        33551.0        NaN
132 2017-01-01              15886.0       9309.0        25195.0        NaN
133 2017-02-01              17357.0      10191.0        27548.0        NaN
134 2017-03-01              18685.0      11979.0        30664.0        NaN
135 2017-04-01              18371.0      11888.0        30259.0        NaN
136 2017-05-01              20324.0      12580.0        32904.0        NaN
137 2017-06-01              19336.0      11690.0        31026.0        NaN
138 2017-07-01              21406.0      12588.0        33994.0        NaN
139 2017-08-01              20567.0      11727.0        32294.0        NaN
140 2017-09-01              20814.0      11057.0        31871.0        NaN
141 2017-10-01              19649.0      10113.0        29762.0        NaN
142 2017-11-01              20047.0      10252.0        30299.0        NaN
143 2017-12-01              22695.0       9913.0        32608.0        NaN
144 2018-01-01              16272.0       7808.0        24080.0        NaN
145 2018-02-01              -8578.0       8578.0        25889.0        NaN
146 2018-03-01              21332.0      10527.0        31859.0        NaN
147 2018-04-01              20416.0       9947.0        30363.0        NaN
148 2018-05-01              22633.0      10929.0        33562.0        NaN
149 2018-06-01              20679.0      10319.0        30998.0        NaN
150 2018-07-01              23117.0      10702.0        33819.0        NaN
151 2018-08-01              22924.0       9692.0        32616.0        NaN
152 2018-09-01              21616.0      10114.0        31730.0        NaN
153 2018-10-01              20671.0       9697.0        30368.0        NaN
154 2018-11-01              20006.0       8091.0        28097.0        NaN
155 2018-12-01              24518.0       9884.0        34402.0        NaN
156 2019-01-01              16005.0       7352.0        23357.0        NaN
157 2019-02-01              13888.0       5905.0        19793.0        NaN
158 2019-03-01              17049.0       6476.0        23525.0        NaN
159 2019-04-01              20202.0       9382.0        29584.0        NaN
160 2019-05-01              21328.0       9540.0        30868.0        NaN
161 2019-06-01              17616.0       7188.0        24804.0        NaN
162 2019-07-01              18860.0       7694.0        26554.0        NaN
163 2019-08-01              21170.0       8698.0        29868.0        NaN
164 2019-09-01              21812.0       8391.0        30203.0        NaN
165 2019-10-01              22384.0       8869.0        31253.0        NaN
166 2019-11-01              19978.0       7133.0        27111.0        NaN
167 2019-12-01              23699.0       7592.0        31291.0        NaN
168 2020-01-01              20744.0       6652.0        27396.0        NaN
169 2020-02-01              14423.0       5483.0        19906.0        NaN
170 2020-03-01              16783.0       5625.0        22408.0        NaN
171 2020-04-01               6771.0       2678.0         9449.0        NaN
172 2020-05-01              14626.0       5045.0        19671.0        NaN
173 2020-06-01              17160.0       5636.0        22796.0        NaN
174 2020-07-01              19577.0       6193.0        25770.0        NaN
175 2020-08-01              23185.0       7320.0        30505.0        NaN
176 2020-09-01              19276.0       5874.0        25150.0        NaN
177 2020-10-01              19103.0       6182.0        25285.0        NaN
178 2020-11-01              20293.0       5938.0        26231.0        NaN
179 2020-12-01              22429.0       5937.0        28366.0        NaN
180 2021-01-01              18862.0       4958.0        23820.0        NaN
181 2021-02-01              16711.0       4489.0        21200.0        NaN
182 2021-03-01              22283.0       5283.0        27566.0        NaN
183 2021-04-01              29222.0       8076.0        37298.0        NaN
184 2021-05-01              22891.0       6451.0        29342.0        NaN
185 2021-06-01              22199.0       6682.0        28881.0        NaN
186 2021-07-01              23666.0       7226.0        30892.0        NaN
187 2021-08-01              16901.0      21676.0        21676.0        NaN
188 2021-09-01              14109.0       4021.0        18130.0        NaN
189 2021-10-01              17447.0       5041.0        22488.0        NaN
190 2021-11-01              13562.0       3328.0        16890.0        NaN
191 2021-12-01              20876.0       4820.0        25696.0        NaN

# Combine CTA & Auto

In [13]:
merged = cta.merge(auto, how='outer', left_index=True, right_index=True)

In [14]:
merged.shape

(252, 7)

In [15]:
merged.head()

,avg_weekday_rides,avg_saturday_rides,avg_sunday-holiday_rides,monthtotal,new_light_truck_reg,new_car_reg,new_total_reg
date,,,,,,,
2001-01-01,487319.6,220753.3,136573.0,12286897.0,NaN,NaN,NaN
2001-02-01,497416.6,219440.1,147447.5,11415793.0,NaN,NaN,NaN
2001-03-01,503369.6,245850.6,152733.2,12914296.0,NaN,NaN,NaN
2001-04-01,501485.0,242434.5,157367.0,12287737.0,NaN,NaN,NaN
2001-05-01,513900.5,246570.3,171236.2,13148263.0,NaN,NaN,NaN

In [16]:
merged.tail()

,avg_weekday_rides,avg_saturday_rides,avg_sunday-holiday_rides,monthtotal,new_light_truck_reg,new_car_reg,new_total_reg
date,,,,,,,
2021-08-01,NaN,NaN,NaN,NaN,16901.0,21676.0,21676.0
2021-09-01,NaN,NaN,NaN,NaN,14109.0,4021.0,18130.0
2021-10-01,NaN,NaN,NaN,NaN,17447.0,5041.0,22488.0
2021-11-01,NaN,NaN,NaN,NaN,13562.0,3328.0,16890.0
2021-12-01,NaN,NaN,NaN,NaN,20876.0,4820.0,25696.0

# Prep Crashes

In [17]:
crashes

    crash_date  count
0       3/1/13      1
1       4/1/13      0
2       5/1/13      0
3       6/1/13      0
4       7/1/13      0
5       8/1/13      0
6       9/1/13      0
7      10/1/13      0
8      11/1/13      0
9      12/1/13      0
10      1/1/14      2
11      2/1/14      1
12      3/1/14      0
13      4/1/14      0
14      5/1/14      0
15      6/1/14      1
16      7/1/14      0
17      8/1/14      1
18      9/1/14      0
19     10/1/14      0
20     11/1/14      1
21     12/1/14      0
22      1/1/15      2
23      2/1/15      1
24      3/1/15      0
25      4/1/15      3
26      5/1/15      3
27      6/1/15      3
28      7/1/15     15
29      8/1/15    447
30      9/1/15   1524
31     10/1/15   2808
32     11/1/15   2606
33     12/1/15   2416
34      1/1/16   2765
35      2/1/16   2539
36      3/1/16   2916
37      4/1/16   2902
38      5/1/16   3091
39      6/1/16   2831
40      7/1/16   3316
41      8/1/16   4461
42      9/1/16   4709
43     10/1/16   4995
44     11/1/16   4720
45     12/1/16   5052
46      1/1/17   4363
47      2/1/17   4109
48      3/1/17   5105
49      4/1/17   5024
50      5/1/17   5847
51      6/1/17   6212
52      7/1/17   6758
53      8/1/17   7685
54      9/1/17   9038
55     10/1/17  10021
56     11/1/17   9515
57     12/1/17  10108
58      1/1/18   9532
59      2/1/18   8729
60      3/1/18   9319
61      4/1/18   9648
62      5/1/18  10713
63      6/1/18  10601
64      7/1/18  10367
65      8/1/18  10211
66      9/1/18   9931
67     10/1/18  10402
68     11/1/18   9473
69     12/1/18  10021
70      1/1/19   9116
71      2/1/19   8625
72      3/1/19   9748
73      4/1/19   9446
74      5/1/19  10708
75      6/1/19  10706
76      7/1/19  10659
77      8/1/19   9940
78      9/1/19   9815
79     10/1/19   9938
80     11/1/19   9640
81     12/1/19   9417
82      1/1/20   8680
83      2/1/20   9019
84      3/1/20   6672
85      4/1/20   4431
86      5/1/20   6547
87      6/1/20   7685
88      7/1/20   9043
89      8/1/20   9161
90      9/1/20   8290
91     10/1/20   8357
92     11/1/20   6962
93     12/1/20   7258
94      1/1/21   7076
95      2/1/21   8399
96      3/1/21   7685
97      4/1/21   8169
98      5/1/21   9651
99      6/1/21  10339
100     7/1/21  10015
101     8/1/21   9989
102     9/1/21   9897
103    10/1/21  10264
104    11/1/21   8763
105    12/1/21   8472
106     1/1/22   3781

In [18]:
crashes.dtypes

crash_date    object
count          int64
dtype: object

In [19]:
crashes.rename(columns={'crash_date':'date'},inplace=True)
crashes['date']=pd.to_datetime(crashes['date'])
crashes.dtypes

date     datetime64[ns]
count             int64
dtype: object

In [20]:
crashes.set_index('date',inplace=True)
crashes.sort_index(inplace=True)

In [21]:
crashes

            count
date
2013-03-01      1
2013-04-01      0
2013-05-01      0
2013-06-01      0
2013-07-01      0
2013-08-01      0
2013-09-01      0
2013-10-01      0
2013-11-01      0
2013-12-01      0
2014-01-01      2
2014-02-01      1
2014-03-01      0
2014-04-01      0
2014-05-01      0
2014-06-01      1
2014-07-01      0
2014-08-01      1
2014-09-01      0
2014-10-01      0
2014-11-01      1
2014-12-01      0
2015-01-01      2
2015-02-01      1
2015-03-01      0
2015-04-01      3
2015-05-01      3
2015-06-01      3
2015-07-01     15
2015-08-01    447
2015-09-01   1524
2015-10-01   2808
2015-11-01   2606
2015-12-01   2416
2016-01-01   2765
2016-02-01   2539
2016-03-01   2916
2016-04-01   2902
2016-05-01   3091
2016-06-01   2831
2016-07-01   3316
2016-08-01   4461
2016-09-01   4709
2016-10-01   4995
2016-11-01   4720
2016-12-01   5052
2017-01-01   4363
2017-02-01   4109
2017-03-01   5105
2017-04-01   5024
2017-05-01   5847
2017-06-01   6212
2017-07-01   6758
2017-08-01   7685
2017-09-01   9038
2017-10-01  10021
2017-11-01   9515
2017-12-01  10108
2018-01-01   9532
2018-02-01   8729
2018-03-01   9319
2018-04-01   9648
2018-05-01  10713
2018-06-01  10601
2018-07-01  10367
2018-08-01  10211
2018-09-01   9931
2018-10-01  10402
2018-11-01   9473
2018-12-01  10021
2019-01-01   9116
2019-02-01   8625
2019-03-01   9748
2019-04-01   9446
2019-05-01  10708
2019-06-01  10706
2019-07-01  10659
2019-08-01   9940
2019-09-01   9815
2019-10-01   9938
2019-11-01   9640
2019-12-01   9417
2020-01-01   8680
2020-02-01   9019
2020-03-01   6672
2020-04-01   4431
2020-05-01   6547
2020-06-01   7685
2020-07-01   9043
2020-08-01   9161
2020-09-01   8290
2020-10-01   8357
2020-11-01   6962
2020-12-01   7258
2021-01-01   7076
2021-02-01   8399
2021-03-01   7685
2021-04-01   8169
2021-05-01   9651
2021-06-01  10339
2021-07-01  10015
2021-08-01   9989
2021-09-01   9897
2021-10-01  10264
2021-11-01   8763
2021-12-01   8472
2022-01-01   3781

# Merge in Crashes

In [22]:
merged = merged.merge(crashes, how='outer', left_index=True, right_index=True)

In [23]:
crashes.shape

(107, 1)

In [24]:
merged.shape

(253, 8)

In [25]:
merged

,avg_weekday_rides,avg_saturday_rides,avg_sunday-holiday_rides,monthtotal,new_light_truck_reg,new_car_reg,new_total_reg,count
date,,,,,,,,
2001-01-01,487319.6,220753.3,136573.0,12286897.0,NaN,NaN,NaN,NaN
2001-02-01,497416.6,219440.1,147447.5,11415793.0,NaN,NaN,NaN,NaN
2001-03-01,503369.6,245850.6,152733.2,12914296.0,NaN,NaN,NaN,NaN
2001-04-01,501485.0,242434.5,157367.0,12287737.0,NaN,NaN,NaN,NaN
2001-05-01,513900.5,246570.3,171236.2,13148263.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2021-09-01,NaN,NaN,NaN,NaN,14109.0,4021.0,18130.0,9897.0
2021-10-01,NaN,NaN,NaN,NaN,17447.0,5041.0,22488.0,10264.0
2021-11-01,NaN,NaN,NaN,NaN,13562.0,3328.0,16890.0,8763.0
2021-12-01,NaN,NaN,NaN,NaN,20876.0,4820.0,25696.0,8472.0
2022-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3781.0

# Prep Covid

In [26]:
covid

,Date,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,C7_Restrictions on internal movement,C8_International travel controls,E1_Income support,E2_Debt/contract relief,H1_Public information campaigns,H1_Flag,H2_Testing policy,H3_Contact tracing,H6_Facial Coverings,H7_Vaccination policy,H8_Protection of elderly people,ConfirmedCases,ConfirmedDeaths,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,1/1/20,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
1,2/1/20,0,0,0,0,0,0,0,0,0,0,1,0.0,1,1,0,0,0,2.0,0.0,2.78,2.78,4.76,4.76,6.77,6.77,7.74,7.74,0.0,0.0
2,3/1/20,0,0,0,0,0,0,0,0,0,0,1,1.0,1,1,0,0,0,3.0,0.0,5.56,5.56,9.52,9.52,8.33,8.33,9.52,9.52,0.0,0.0
3,4/1/20,3,3,2,4,0,2,2,3,2,2,2,1.0,1,1,0,0,1,6980.0,141.0,82.41,82.41,82.14,82.14,64.58,64.58,61.31,61.31,87.5,87.5
4,5/1/20,3,3,2,4,0,2,2,3,2,2,2,1.0,1,1,2,0,1,56055.0,2457.0,82.41,82.41,82.14,82.14,67.71,67.71,64.88,64.88,87.5,87.5
5,6/1/20,3,1,2,4,0,2,2,3,2,2,2,1.0,2,1,2,0,1,121234.0,5412.0,75.00,75.00,75.00,75.00,65.62,65.62,62.50,62.50,87.5,87.5
6,7/1/20,3,1,1,3,0,1,1,3,2,2,2,1.0,2,1,2,0,1,144013.0,6951.0,55.56,55.56,63.81,63.81,54.69,54.69,50.00,50.00,87.5,87.5
7,8/1/20,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,2,0,1,181754.0,7700.0,58.33,58.33,63.81,63.81,52.08,52.08,54.17,54.17,37.5,37.5
8,9/1/20,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,2,0,1,238216.0,8273.0,55.09,55.09,58.33,58.33,50.26,50.26,52.08,52.08,37.5,37.5
9,10/1/20,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,4,0,1,297884.0,8940.0,55.09,55.09,58.33,58.33,52.60,52.60,54.76,54.76,37.5,37.5
10,11/1/20,2,1,1,4,0,1,2,3,1,1,2,1.0,3,1,4,0,1,423527.0,10075.0,56.02,56.02,60.24,60.24,53.12,53.12,55.36,55.36,37.5,37.5
11,12/1/20,2,1,2,4,0,2,2,3,1,2,2,1.0,3,1,3,0,1,738846.0,13131.0,66.67,66.67,64.29,64.29,61.46,61.46,61.31,61.31,62.5,62.5
12,1/1/21,2,1,2,4,0,2,2,3,1,2,2,1.0,3,1,3,2,1,963389.0,17978.0,66.67,66.67,64.29,64.29,63.96,63.96,64.17,64.17,62.5,62.5
13,2/1/21,2,1,2,4,0,1,2,3,1,2,2,1.0,3,1,3,2,3,1128613.0,21273.0,62.96,62.96,63.10,63.10,65.00,65.00,65.36,65.36,62.5,62.5
14,3/1/21,2,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,3,3,1187839.0,22759.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
15,4/1/21,2,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,3,3,1248111.0,23601.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
16,5/1/21,1,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,5,3,1337868.0,24330.0,52.78,52.78,60.24,60.24,63.80,63.80,63.99,63.99,62.5,62.5
17,6/1/21,1,1,1,3,0,1,2,3,1,2,2,1.0,3,1,2,5,3,1382587.0,25233.0,52.78,52.78,60.24,60.24,61.46,61.46,61.31,61.31,62.5,62.5
18,7/1/21,1,0,1,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1392196.0,25670.0,34.26,34.26,51.19,51.19,46.88,46.88,44.64,44.64,62.5,62.5
19,8/1/21,0,0,1,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1419611.0,25873.0,30.56,30.56,44.05,44.05,44.79,44.79,42.26,42.26,62.5,62.5
20,9/1/21,0,0,0,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1528120.0,26412.0,25.00,25.00,34.52,34.52,42.71,42.71,39.88,39.88,62.5,62.5
21,10/1/21,0,0,0,0,0,0,1,3,1,1,2,1.0,3,1,2,5,2,1630864.0,27450.0,25.00,25.00,34.52,34.52,41.67,41.67,42.26,42.26,37.5,37.5
22,11/1/21,0,0,0,0,0,0,1,3,1,1,2,1.0,3,2,2,5,2,1701649.0,28267.0,25.00,25.00,34.52,34.52,44.79,44.79,45.83,45.83,37.5,37.5
23,12/1/21,0,0,0,0,0,0,1,3,1,1,2,1.0,3,2,2,5,2,1815994.0,28892.0,25.00,25.00,34.52,34.52,44.79,44.79,45.83,45.83,37.5,37.5

In [27]:
covid.dtypes

Date                                     object
C1_School closing                         int64
C2_Workplace closing                      int64
C3_Cancel public events                   int64
C4_Restrictions on gatherings             int64
C5_Close public transport                 int64
C6_Stay at home requirements              int64
C7_Restrictions on internal movement      int64
C8_International travel controls          int64
E1_Income support                         int64
E2_Debt/contract relief                   int64
H1_Public information campaigns           int64
H1_Flag                                 float64
H2_Testing policy                         int64
H3_Contact tracing                        int64
H6_Facial Coverings                       int64
H7_Vaccination policy                     int64
H8_Protection of elderly people           int64
ConfirmedCases                          float64
ConfirmedDeaths                         float64
StringencyIndex                         float64
StringencyIndexForDisplay               float64
StringencyLegacyIndex                   float64
StringencyLegacyIndexForDisplay         float64
GovernmentResponseIndex                 float64
GovernmentResponseIndexForDisplay       float64
ContainmentHealthIndex                  float64
ContainmentHealthIndexForDisplay        float64
EconomicSupportIndex                    float64
EconomicSupportIndexForDisplay          float64
dtype: object

In [28]:
covid.rename(columns={'Date':'date'},inplace=True)
covid['date']=pd.to_datetime(covid['date'])
covid.dtypes

date                                    datetime64[ns]
C1_School closing                                int64
C2_Workplace closing                             int64
C3_Cancel public events                          int64
C4_Restrictions on gatherings                    int64
C5_Close public transport                        int64
C6_Stay at home requirements                     int64
C7_Restrictions on internal movement             int64
C8_International travel controls                 int64
E1_Income support                                int64
E2_Debt/contract relief                          int64
H1_Public information campaigns                  int64
H1_Flag                                        float64
H2_Testing policy                                int64
H3_Contact tracing                               int64
H6_Facial Coverings                              int64
H7_Vaccination policy                            int64
H8_Protection of elderly people                  int64
ConfirmedCases                                 float64
ConfirmedDeaths                                float64
StringencyIndex                                float64
StringencyIndexForDisplay                      float64
StringencyLegacyIndex                          float64
StringencyLegacyIndexForDisplay                float64
GovernmentResponseIndex                        float64
GovernmentResponseIndexForDisplay              float64
ContainmentHealthIndex                         float64
ContainmentHealthIndexForDisplay               float64
EconomicSupportIndex                           float64
EconomicSupportIndexForDisplay                 float64
dtype: object

In [29]:
covid.set_index('date',inplace=True)
covid.sort_index(inplace=True)

In [30]:
covid

,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,C7_Restrictions on internal movement,C8_International travel controls,E1_Income support,E2_Debt/contract relief,H1_Public information campaigns,H1_Flag,H2_Testing policy,H3_Contact tracing,H6_Facial Coverings,H7_Vaccination policy,H8_Protection of elderly people,ConfirmedCases,ConfirmedDeaths,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2020-01-01,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
2020-02-01,0,0,0,0,0,0,0,0,0,0,1,0.0,1,1,0,0,0,2.0,0.0,2.78,2.78,4.76,4.76,6.77,6.77,7.74,7.74,0.0,0.0
2020-03-01,0,0,0,0,0,0,0,0,0,0,1,1.0,1,1,0,0,0,3.0,0.0,5.56,5.56,9.52,9.52,8.33,8.33,9.52,9.52,0.0,0.0
2020-04-01,3,3,2,4,0,2,2,3,2,2,2,1.0,1,1,0,0,1,6980.0,141.0,82.41,82.41,82.14,82.14,64.58,64.58,61.31,61.31,87.5,87.5
2020-05-01,3,3,2,4,0,2,2,3,2,2,2,1.0,1,1,2,0,1,56055.0,2457.0,82.41,82.41,82.14,82.14,67.71,67.71,64.88,64.88,87.5,87.5
2020-06-01,3,1,2,4,0,2,2,3,2,2,2,1.0,2,1,2,0,1,121234.0,5412.0,75.00,75.00,75.00,75.00,65.62,65.62,62.50,62.50,87.5,87.5
2020-07-01,3,1,1,3,0,1,1,3,2,2,2,1.0,2,1,2,0,1,144013.0,6951.0,55.56,55.56,63.81,63.81,54.69,54.69,50.00,50.00,87.5,87.5
2020-08-01,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,2,0,1,181754.0,7700.0,58.33,58.33,63.81,63.81,52.08,52.08,54.17,54.17,37.5,37.5
2020-09-01,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,2,0,1,238216.0,8273.0,55.09,55.09,58.33,58.33,50.26,50.26,52.08,52.08,37.5,37.5
2020-10-01,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,4,0,1,297884.0,8940.0,55.09,55.09,58.33,58.33,52.60,52.60,54.76,54.76,37.5,37.5
2020-11-01,2,1,1,4,0,1,2,3,1,1,2,1.0,3,1,4,0,1,423527.0,10075.0,56.02,56.02,60.24,60.24,53.12,53.12,55.36,55.36,37.5,37.5
2020-12-01,2,1,2,4,0,2,2,3,1,2,2,1.0,3,1,3,0,1,738846.0,13131.0,66.67,66.67,64.29,64.29,61.46,61.46,61.31,61.31,62.5,62.5
2021-01-01,2,1,2,4,0,2,2,3,1,2,2,1.0,3,1,3,2,1,963389.0,17978.0,66.67,66.67,64.29,64.29,63.96,63.96,64.17,64.17,62.5,62.5
2021-02-01,2,1,2,4,0,1,2,3,1,2,2,1.0,3,1,3,2,3,1128613.0,21273.0,62.96,62.96,63.10,63.10,65.00,65.00,65.36,65.36,62.5,62.5
2021-03-01,2,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,3,3,1187839.0,22759.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
2021-04-01,2,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,3,3,1248111.0,23601.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
2021-05-01,1,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,5,3,1337868.0,24330.0,52.78,52.78,60.24,60.24,63.80,63.80,63.99,63.99,62.5,62.5
2021-06-01,1,1,1,3,0,1,2,3,1,2,2,1.0,3,1,2,5,3,1382587.0,25233.0,52.78,52.78,60.24,60.24,61.46,61.46,61.31,61.31,62.5,62.5
2021-07-01,1,0,1,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1392196.0,25670.0,34.26,34.26,51.19,51.19,46.88,46.88,44.64,44.64,62.5,62.5
2021-08-01,0,0,1,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1419611.0,25873.0,30.56,30.56,44.05,44.05,44.79,44.79,42.26,42.26,62.5,62.5
2021-09-01,0,0,0,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1528120.0,26412.0,25.00,25.00,34.52,34.52,42.71,42.71,39.88,39.88,62.5,62.5
2021-10-01,0,0,0,0,0,0,1,3,1,1,2,1.0,3,1,2,5,2,1630864.0,27450.0,25.00,25.00,34.52,34.52,41.67,41.67,42.26,42.26,37.5,37.5
2021-11-01,0,0,0,0,0,0,1,3,1,1,2,1.0,3,2,2,5,2,1701649.0,28267.0,25.00,25.00,34.52,34.52,44.79,44.79,45.83,45.83,37.5,37.5
2021-12-01,0,0,0,0,0,0,1,3,1,1,2,1.0,3,2,2,5,2,1815994.0,28892.0,25.00,25.00,34.52,34.52,44.79,44.79,45.83,45.83,37.5,37.5

In [31]:
merged = merged.merge(covid, how='outer', left_index=True, right_index=True)

In [32]:
merged.shape

(253, 37)

In [33]:
merged.isna().sum()

avg_weekday_rides                         6
avg_saturday_rides                        6
avg_sunday-holiday_rides                  6
monthtotal                                6
new_light_truck_reg                      84
new_car_reg                              84
new_total_reg                            82
count                                   146
C1_School closing                       229
C2_Workplace closing                    229
C3_Cancel public events                 229
C4_Restrictions on gatherings           229
C5_Close public transport               229
C6_Stay at home requirements            229
C7_Restrictions on internal movement    229
C8_International travel controls        229
E1_Income support                       229
E2_Debt/contract relief                 229
H1_Public information campaigns         229
H1_Flag                                 230
H2_Testing policy                       229
H3_Contact tracing                      229
H6_Facial Coverings                     229
H7_Vaccination policy                   229
H8_Protection of elderly people         229
ConfirmedCases                          230
ConfirmedDeaths                         230
StringencyIndex                         229
StringencyIndexForDisplay               229
StringencyLegacyIndex                   229
StringencyLegacyIndexForDisplay         229
GovernmentResponseIndex                 229
GovernmentResponseIndexForDisplay       229
ContainmentHealthIndex                  229
ContainmentHealthIndexForDisplay        229
EconomicSupportIndex                    229
EconomicSupportIndexForDisplay          229
dtype: int64

In [34]:
merged.rename(columns={'count':'car_crashes'},inplace=True)

In [35]:
merged.loc[merged['monthtotal'].isna() == False]

,avg_weekday_rides,avg_saturday_rides,avg_sunday-holiday_rides,monthtotal,new_light_truck_reg,new_car_reg,new_total_reg,car_crashes,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,C7_Restrictions on internal movement,C8_International travel controls,E1_Income support,E2_Debt/contract relief,H1_Public information campaigns,H1_Flag,H2_Testing policy,H3_Contact tracing,H6_Facial Coverings,H7_Vaccination policy,H8_Protection of elderly people,ConfirmedCases,ConfirmedDeaths,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2001-01-01,487319.6,220753.3,136573.0,12286897.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-02-01,497416.6,219440.1,147447.5,11415793.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-03-01,503369.6,245850.6,152733.2,12914296.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-04-01,501485.0,242434.5,157367.0,12287737.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-05-01,513900.5,246570.3,171236.2,13148263.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-01,135312.4,113530.8,83009.1,3898318.0,22283.0,5283.0,27566.0,7685.0,2.0,1.0,1.0,3.0,0.0,1.0,2.0,3.0,1.0,2.0,2.0,1.0,3.0,1.0,4.0,3.0,3.0,1187839.0,22759.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
2021-04-01,148614.3,120363.0,90308.6,4112171.0,29222.0,8076.0,37298.0,8169.0,2.0,1.0,1.0,3.0,0.0,1.0,2.0,3.0,1.0,2.0,2.0,1.0,3.0,1.0,4.0,3.0,3.0,1248111.0,23601.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
2021-05-01,166836.1,148655.2,114718.4,4768231.0,22891.0,6451.0,29342.0,9651.0,1.0,1.0,1.0,3.0,0.0,1.0,2.0,3.0,1.0,2.0,2.0,1.0,3.0,1.0,4.0,5.0,3.0,1337868.0,24330.0,52.78,52.78,60.24,60.24,63.80,63.80,63.99,63.99,62.5,62.5
2021-06-01,199886.2,177984.6,139961.0,5669251.0,22199.0,6682.0,28881.0,10339.0,1.0,1.0,1.0,3.0,0.0,1.0,2.0,3.0,1.0,2.0,2.0,1.0,3.0,1.0,2.0,5.0,3.0,1382587.0,25233.0,52.78,52.78,60.24,60.24,61.46,61.46,61.31,61.31,62.5,62.5
2021-07-01,236309.6,213547.2,153024.0,6795339.0,23666.0,7226.0,30892.0,10015.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,3.0,1.0,2.0,2.0,1.0,3.0,1.0,2.0,5.0,1.0,1392196.0,25670.0,34.26,34.26,51.19,51.19,46.88,46.88,44.64,44.64,62.5,62.5

In [36]:
merge_limited = merged.loc[merged['new_total_reg'].isna()==False]

In [37]:
merged.to_csv('../capstone-data/merged_na.csv')
merge_limited.to_csv('../capstone-data/merge_limited.csv')