In [95]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)

In [96]:
covid = pd.read_csv('../capstone-data/covid-restrictions.csv')
cta = pd.read_csv('../capstone-data/cta-monthly-primary.csv')
auto = pd.read_excel('../capstone-data/agg_auto.xlsx')
crashes = pd.read_csv('../capstone-data/crash_fin.csv')

# Prep CTA

In [97]:
cta.dtypes

month_beginning              object
avg_weekday_rides           float64
avg_saturday_rides          float64
avg_sunday-holiday_rides    float64
monthtotal                  float64
dtype: object

In [98]:
cta.rename(columns={'month_beginning':'date'},inplace=True)

In [99]:
cta['date']=pd.to_datetime(cta['date'])

In [100]:
cta.dtypes

date                        datetime64[ns]
avg_weekday_rides                  float64
avg_saturday_rides                 float64
avg_sunday-holiday_rides           float64
monthtotal                         float64
dtype: object

In [101]:
cta.set_index('date',inplace=True)
cta.sort_index(inplace=True)

# Prep Auto

In [102]:
auto.rename(columns={'Unnamed: 0':'date'},inplace=True)

In [103]:
auto.drop(columns={'Unnamed: 4'},inplace=True)

In [104]:
auto.dtypes

date                   datetime64[ns]
new_light_truck_reg           float64
new_car_reg                   float64
new_total_reg                 float64
dtype: object

In [105]:
auto.set_index('date',inplace=True)
auto.sort_index(inplace=True)

In [106]:
auto.head()

            new_light_truck_reg  new_car_reg  new_total_reg
date
2006-01-01              13166.0      13961.0        27127.0
2006-02-01              11239.5      12597.0        23836.5
2006-03-01              11716.5      13620.5        25337.0
2006-04-01              11716.5      13620.5        25337.0
2006-05-01              11177.5      14052.5        25230.0

# Combine CTA & Auto

In [107]:
merged = cta.merge(auto, how='outer', left_index=True, right_index=True)

In [108]:
merged.shape

(252, 7)

In [109]:
merged.head()

,avg_weekday_rides,avg_saturday_rides,avg_sunday-holiday_rides,monthtotal,new_light_truck_reg,new_car_reg,new_total_reg
date,,,,,,,
2001-01-01,487319.6,220753.3,136573.0,12286897.0,NaN,NaN,NaN
2001-02-01,497416.6,219440.1,147447.5,11415793.0,NaN,NaN,NaN
2001-03-01,503369.6,245850.6,152733.2,12914296.0,NaN,NaN,NaN
2001-04-01,501485.0,242434.5,157367.0,12287737.0,NaN,NaN,NaN
2001-05-01,513900.5,246570.3,171236.2,13148263.0,NaN,NaN,NaN

In [110]:
merged.tail()

,avg_weekday_rides,avg_saturday_rides,avg_sunday-holiday_rides,monthtotal,new_light_truck_reg,new_car_reg,new_total_reg
date,,,,,,,
2021-08-01,NaN,NaN,NaN,NaN,16901.0,21676.0,21676.0
2021-09-01,NaN,NaN,NaN,NaN,14109.0,4021.0,18130.0
2021-10-01,NaN,NaN,NaN,NaN,17447.0,5041.0,22488.0
2021-11-01,NaN,NaN,NaN,NaN,13562.0,3328.0,16890.0
2021-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Prep Crashes

In [111]:
crashes

      crash_date  count
0     2013-03-03    1.0
1     2014-01-18    1.0
2     2014-01-21    1.0
3     2014-02-24    1.0
4     2014-06-25    1.0
...          ...    ...
2387  2022-01-13  216.0
2388  2022-01-14  264.0
2389  2022-01-15  265.0
2390  2022-01-16  149.0
2391  2022-01-17    7.0

[2392 rows x 2 columns]

In [112]:
crashes.dtypes

crash_date     object
count         float64
dtype: object

In [113]:
crashes.rename(columns={'crash_date':'date'},inplace=True)
crashes['date']=pd.to_datetime(crashes['date'])
crashes.dtypes

date     datetime64[ns]
count           float64
dtype: object

In [114]:
crashes.set_index('date',inplace=True)
crashes.sort_index(inplace=True)

In [115]:
crashes

            count
date
2013-03-03    1.0
2014-01-18    1.0
2014-01-21    1.0
2014-02-24    1.0
2014-06-25    1.0
...           ...
2022-01-13  216.0
2022-01-14  264.0
2022-01-15  265.0
2022-01-16  149.0
2022-01-17    7.0

[2392 rows x 1 columns]

# Merge in Crashes

In [116]:
merged = merged.merge(crashes, how='outer', left_index=True, right_index=True)

In [117]:
crashes.shape

(2392, 1)

In [118]:
merged.shape

(2567, 8)

In [119]:
merged

,avg_weekday_rides,avg_saturday_rides,avg_sunday-holiday_rides,monthtotal,new_light_truck_reg,new_car_reg,new_total_reg,count
date,,,,,,,,
2001-01-01,487319.6,220753.3,136573.0,12286897.0,NaN,NaN,NaN,NaN
2001-02-01,497416.6,219440.1,147447.5,11415793.0,NaN,NaN,NaN,NaN
2001-03-01,503369.6,245850.6,152733.2,12914296.0,NaN,NaN,NaN,NaN
2001-04-01,501485.0,242434.5,157367.0,12287737.0,NaN,NaN,NaN,NaN
2001-05-01,513900.5,246570.3,171236.2,13148263.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
2022-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,216.0
2022-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264.0
2022-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,265.0
2022-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149.0
2022-01-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0

# Prep Covid

In [120]:
covid

,Date,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,C7_Restrictions on internal movement,C8_International travel controls,E1_Income support,E2_Debt/contract relief,H1_Public information campaigns,H1_Flag,H2_Testing policy,H3_Contact tracing,H6_Facial Coverings,H7_Vaccination policy,H8_Protection of elderly people,ConfirmedCases,ConfirmedDeaths,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
0,1/1/20,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
1,2/1/20,0,0,0,0,0,0,0,0,0,0,1,0.0,1,1,0,0,0,2.0,0.0,2.78,2.78,4.76,4.76,6.77,6.77,7.74,7.74,0.0,0.0
2,3/1/20,0,0,0,0,0,0,0,0,0,0,1,1.0,1,1,0,0,0,3.0,0.0,5.56,5.56,9.52,9.52,8.33,8.33,9.52,9.52,0.0,0.0
3,4/1/20,3,3,2,4,0,2,2,3,2,2,2,1.0,1,1,0,0,1,6980.0,141.0,82.41,82.41,82.14,82.14,64.58,64.58,61.31,61.31,87.5,87.5
4,5/1/20,3,3,2,4,0,2,2,3,2,2,2,1.0,1,1,2,0,1,56055.0,2457.0,82.41,82.41,82.14,82.14,67.71,67.71,64.88,64.88,87.5,87.5
5,6/1/20,3,1,2,4,0,2,2,3,2,2,2,1.0,2,1,2,0,1,121234.0,5412.0,75.00,75.00,75.00,75.00,65.62,65.62,62.50,62.50,87.5,87.5
6,7/1/20,3,1,1,3,0,1,1,3,2,2,2,1.0,2,1,2,0,1,144013.0,6951.0,55.56,55.56,63.81,63.81,54.69,54.69,50.00,50.00,87.5,87.5
7,8/1/20,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,2,0,1,181754.0,7700.0,58.33,58.33,63.81,63.81,52.08,52.08,54.17,54.17,37.5,37.5
8,9/1/20,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,2,0,1,238216.0,8273.0,55.09,55.09,58.33,58.33,50.26,50.26,52.08,52.08,37.5,37.5
9,10/1/20,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,4,0,1,297884.0,8940.0,55.09,55.09,58.33,58.33,52.60,52.60,54.76,54.76,37.5,37.5
10,11/1/20,2,1,1,4,0,1,2,3,1,1,2,1.0,3,1,4,0,1,423527.0,10075.0,56.02,56.02,60.24,60.24,53.12,53.12,55.36,55.36,37.5,37.5
11,12/1/20,2,1,2,4,0,2,2,3,1,2,2,1.0,3,1,3,0,1,738846.0,13131.0,66.67,66.67,64.29,64.29,61.46,61.46,61.31,61.31,62.5,62.5
12,1/1/21,2,1,2,4,0,2,2,3,1,2,2,1.0,3,1,3,2,1,963389.0,17978.0,66.67,66.67,64.29,64.29,63.96,63.96,64.17,64.17,62.5,62.5
13,2/1/21,2,1,2,4,0,1,2,3,1,2,2,1.0,3,1,3,2,3,1128613.0,21273.0,62.96,62.96,63.10,63.10,65.00,65.00,65.36,65.36,62.5,62.5
14,3/1/21,2,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,3,3,1187839.0,22759.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
15,4/1/21,2,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,3,3,1248111.0,23601.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
16,5/1/21,1,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,5,3,1337868.0,24330.0,52.78,52.78,60.24,60.24,63.80,63.80,63.99,63.99,62.5,62.5
17,6/1/21,1,1,1,3,0,1,2,3,1,2,2,1.0,3,1,2,5,3,1382587.0,25233.0,52.78,52.78,60.24,60.24,61.46,61.46,61.31,61.31,62.5,62.5
18,7/1/21,1,0,1,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1392196.0,25670.0,34.26,34.26,51.19,51.19,46.88,46.88,44.64,44.64,62.5,62.5
19,8/1/21,0,0,1,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1419611.0,25873.0,30.56,30.56,44.05,44.05,44.79,44.79,42.26,42.26,62.5,62.5
20,9/1/21,0,0,0,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1528120.0,26412.0,25.00,25.00,34.52,34.52,42.71,42.71,39.88,39.88,62.5,62.5
21,10/1/21,0,0,0,0,0,0,1,3,1,1,2,1.0,3,1,2,5,2,1630864.0,27450.0,25.00,25.00,34.52,34.52,41.67,41.67,42.26,42.26,37.5,37.5
22,11/1/21,0,0,0,0,0,0,1,3,1,1,2,1.0,3,2,2,5,2,1701649.0,28267.0,25.00,25.00,34.52,34.52,44.79,44.79,45.83,45.83,37.5,37.5
23,12/1/21,0,0,0,0,0,0,1,3,1,1,2,1.0,3,2,2,5,2,1815994.0,28892.0,25.00,25.00,34.52,34.52,44.79,44.79,45.83,45.83,37.5,37.5

In [121]:
covid.dtypes

Date                                     object
C1_School closing                         int64
C2_Workplace closing                      int64
C3_Cancel public events                   int64
C4_Restrictions on gatherings             int64
C5_Close public transport                 int64
C6_Stay at home requirements              int64
C7_Restrictions on internal movement      int64
C8_International travel controls          int64
E1_Income support                         int64
E2_Debt/contract relief                   int64
H1_Public information campaigns           int64
H1_Flag                                 float64
H2_Testing policy                         int64
H3_Contact tracing                        int64
H6_Facial Coverings                       int64
H7_Vaccination policy                     int64
H8_Protection of elderly people           int64
ConfirmedCases                          float64
ConfirmedDeaths                         float64
StringencyIndex                         float64
StringencyIndexForDisplay               float64
StringencyLegacyIndex                   float64
StringencyLegacyIndexForDisplay         float64
GovernmentResponseIndex                 float64
GovernmentResponseIndexForDisplay       float64
ContainmentHealthIndex                  float64
ContainmentHealthIndexForDisplay        float64
EconomicSupportIndex                    float64
EconomicSupportIndexForDisplay          float64
dtype: object

In [122]:
covid.rename(columns={'Date':'date'},inplace=True)
covid['date']=pd.to_datetime(covid['date'])
covid.dtypes

date                                    datetime64[ns]
C1_School closing                                int64
C2_Workplace closing                             int64
C3_Cancel public events                          int64
C4_Restrictions on gatherings                    int64
C5_Close public transport                        int64
C6_Stay at home requirements                     int64
C7_Restrictions on internal movement             int64
C8_International travel controls                 int64
E1_Income support                                int64
E2_Debt/contract relief                          int64
H1_Public information campaigns                  int64
H1_Flag                                        float64
H2_Testing policy                                int64
H3_Contact tracing                               int64
H6_Facial Coverings                              int64
H7_Vaccination policy                            int64
H8_Protection of elderly people                  int64
ConfirmedCases                                 float64
ConfirmedDeaths                                float64
StringencyIndex                                float64
StringencyIndexForDisplay                      float64
StringencyLegacyIndex                          float64
StringencyLegacyIndexForDisplay                float64
GovernmentResponseIndex                        float64
GovernmentResponseIndexForDisplay              float64
ContainmentHealthIndex                         float64
ContainmentHealthIndexForDisplay               float64
EconomicSupportIndex                           float64
EconomicSupportIndexForDisplay                 float64
dtype: object

In [123]:
covid.set_index('date',inplace=True)
covid.sort_index(inplace=True)

In [124]:
covid

,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,C7_Restrictions on internal movement,C8_International travel controls,E1_Income support,E2_Debt/contract relief,H1_Public information campaigns,H1_Flag,H2_Testing policy,H3_Contact tracing,H6_Facial Coverings,H7_Vaccination policy,H8_Protection of elderly people,ConfirmedCases,ConfirmedDeaths,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2020-01-01,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0
2020-02-01,0,0,0,0,0,0,0,0,0,0,1,0.0,1,1,0,0,0,2.0,0.0,2.78,2.78,4.76,4.76,6.77,6.77,7.74,7.74,0.0,0.0
2020-03-01,0,0,0,0,0,0,0,0,0,0,1,1.0,1,1,0,0,0,3.0,0.0,5.56,5.56,9.52,9.52,8.33,8.33,9.52,9.52,0.0,0.0
2020-04-01,3,3,2,4,0,2,2,3,2,2,2,1.0,1,1,0,0,1,6980.0,141.0,82.41,82.41,82.14,82.14,64.58,64.58,61.31,61.31,87.5,87.5
2020-05-01,3,3,2,4,0,2,2,3,2,2,2,1.0,1,1,2,0,1,56055.0,2457.0,82.41,82.41,82.14,82.14,67.71,67.71,64.88,64.88,87.5,87.5
2020-06-01,3,1,2,4,0,2,2,3,2,2,2,1.0,2,1,2,0,1,121234.0,5412.0,75.00,75.00,75.00,75.00,65.62,65.62,62.50,62.50,87.5,87.5
2020-07-01,3,1,1,3,0,1,1,3,2,2,2,1.0,2,1,2,0,1,144013.0,6951.0,55.56,55.56,63.81,63.81,54.69,54.69,50.00,50.00,87.5,87.5
2020-08-01,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,2,0,1,181754.0,7700.0,58.33,58.33,63.81,63.81,52.08,52.08,54.17,54.17,37.5,37.5
2020-09-01,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,2,0,1,238216.0,8273.0,55.09,55.09,58.33,58.33,50.26,50.26,52.08,52.08,37.5,37.5
2020-10-01,3,1,1,3,0,1,2,3,1,1,2,1.0,3,1,4,0,1,297884.0,8940.0,55.09,55.09,58.33,58.33,52.60,52.60,54.76,54.76,37.5,37.5
2020-11-01,2,1,1,4,0,1,2,3,1,1,2,1.0,3,1,4,0,1,423527.0,10075.0,56.02,56.02,60.24,60.24,53.12,53.12,55.36,55.36,37.5,37.5
2020-12-01,2,1,2,4,0,2,2,3,1,2,2,1.0,3,1,3,0,1,738846.0,13131.0,66.67,66.67,64.29,64.29,61.46,61.46,61.31,61.31,62.5,62.5
2021-01-01,2,1,2,4,0,2,2,3,1,2,2,1.0,3,1,3,2,1,963389.0,17978.0,66.67,66.67,64.29,64.29,63.96,63.96,64.17,64.17,62.5,62.5
2021-02-01,2,1,2,4,0,1,2,3,1,2,2,1.0,3,1,3,2,3,1128613.0,21273.0,62.96,62.96,63.10,63.10,65.00,65.00,65.36,65.36,62.5,62.5
2021-03-01,2,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,3,3,1187839.0,22759.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
2021-04-01,2,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,3,3,1248111.0,23601.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
2021-05-01,1,1,1,3,0,1,2,3,1,2,2,1.0,3,1,4,5,3,1337868.0,24330.0,52.78,52.78,60.24,60.24,63.80,63.80,63.99,63.99,62.5,62.5
2021-06-01,1,1,1,3,0,1,2,3,1,2,2,1.0,3,1,2,5,3,1382587.0,25233.0,52.78,52.78,60.24,60.24,61.46,61.46,61.31,61.31,62.5,62.5
2021-07-01,1,0,1,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1392196.0,25670.0,34.26,34.26,51.19,51.19,46.88,46.88,44.64,44.64,62.5,62.5
2021-08-01,0,0,1,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1419611.0,25873.0,30.56,30.56,44.05,44.05,44.79,44.79,42.26,42.26,62.5,62.5
2021-09-01,0,0,0,0,0,0,1,3,1,2,2,1.0,3,1,2,5,1,1528120.0,26412.0,25.00,25.00,34.52,34.52,42.71,42.71,39.88,39.88,62.5,62.5
2021-10-01,0,0,0,0,0,0,1,3,1,1,2,1.0,3,1,2,5,2,1630864.0,27450.0,25.00,25.00,34.52,34.52,41.67,41.67,42.26,42.26,37.5,37.5
2021-11-01,0,0,0,0,0,0,1,3,1,1,2,1.0,3,2,2,5,2,1701649.0,28267.0,25.00,25.00,34.52,34.52,44.79,44.79,45.83,45.83,37.5,37.5
2021-12-01,0,0,0,0,0,0,1,3,1,1,2,1.0,3,2,2,5,2,1815994.0,28892.0,25.00,25.00,34.52,34.52,44.79,44.79,45.83,45.83,37.5,37.5

In [125]:
merged = merged.merge(covid, how='outer', left_index=True, right_index=True)

In [126]:
merged.shape

(2567, 37)

In [127]:
merged.isna().sum()

avg_weekday_rides                       2320
avg_saturday_rides                      2320
avg_sunday-holiday_rides                2320
monthtotal                              2320
new_light_truck_reg                     2399
new_car_reg                             2399
new_total_reg                           2397
count                                    175
C1_School closing                       2543
C2_Workplace closing                    2543
C3_Cancel public events                 2543
C4_Restrictions on gatherings           2543
C5_Close public transport               2543
C6_Stay at home requirements            2543
C7_Restrictions on internal movement    2543
C8_International travel controls        2543
E1_Income support                       2543
E2_Debt/contract relief                 2543
H1_Public information campaigns         2543
H1_Flag                                 2544
H2_Testing policy                       2543
H3_Contact tracing                      2543
H6_Facial Coverings                     2543
H7_Vaccination policy                   2543
H8_Protection of elderly people         2543
ConfirmedCases                          2544
ConfirmedDeaths                         2544
StringencyIndex                         2543
StringencyIndexForDisplay               2543
StringencyLegacyIndex                   2543
StringencyLegacyIndexForDisplay         2543
GovernmentResponseIndex                 2543
GovernmentResponseIndexForDisplay       2543
ContainmentHealthIndex                  2543
ContainmentHealthIndexForDisplay        2543
EconomicSupportIndex                    2543
EconomicSupportIndexForDisplay          2543
dtype: int64

In [128]:
merged.rename(columns={'count':'car_crashes'},inplace=True)

In [129]:
merged.loc[merged['monthtotal'].isna() == False]

,avg_weekday_rides,avg_saturday_rides,avg_sunday-holiday_rides,monthtotal,new_light_truck_reg,new_car_reg,new_total_reg,car_crashes,C1_School closing,C2_Workplace closing,C3_Cancel public events,C4_Restrictions on gatherings,C5_Close public transport,C6_Stay at home requirements,C7_Restrictions on internal movement,C8_International travel controls,E1_Income support,E2_Debt/contract relief,H1_Public information campaigns,H1_Flag,H2_Testing policy,H3_Contact tracing,H6_Facial Coverings,H7_Vaccination policy,H8_Protection of elderly people,ConfirmedCases,ConfirmedDeaths,StringencyIndex,StringencyIndexForDisplay,StringencyLegacyIndex,StringencyLegacyIndexForDisplay,GovernmentResponseIndex,GovernmentResponseIndexForDisplay,ContainmentHealthIndex,ContainmentHealthIndexForDisplay,EconomicSupportIndex,EconomicSupportIndexForDisplay
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2001-01-01,487319.6,220753.3,136573.0,12286897.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-02-01,497416.6,219440.1,147447.5,11415793.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-03-01,503369.6,245850.6,152733.2,12914296.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-04-01,501485.0,242434.5,157367.0,12287737.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2001-05-01,513900.5,246570.3,171236.2,13148263.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-03-01,135312.4,113530.8,83009.1,3898318.0,22283.0,5283.0,27566.0,239.0,2.0,1.0,1.0,3.0,0.0,1.0,2.0,3.0,1.0,2.0,2.0,1.0,3.0,1.0,4.0,3.0,3.0,1187839.0,22759.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
2021-04-01,148614.3,120363.0,90308.6,4112171.0,29222.0,8076.0,37298.0,266.0,2.0,1.0,1.0,3.0,0.0,1.0,2.0,3.0,1.0,2.0,2.0,1.0,3.0,1.0,4.0,3.0,3.0,1248111.0,23601.0,54.63,54.63,60.24,60.24,62.34,62.34,62.32,62.32,62.5,62.5
2021-05-01,166836.1,148655.2,114718.4,4768231.0,22891.0,6451.0,29342.0,320.0,1.0,1.0,1.0,3.0,0.0,1.0,2.0,3.0,1.0,2.0,2.0,1.0,3.0,1.0,4.0,5.0,3.0,1337868.0,24330.0,52.78,52.78,60.24,60.24,63.80,63.80,63.99,63.99,62.5,62.5
2021-06-01,199886.2,177984.6,139961.0,5669251.0,22199.0,6682.0,28881.0,303.0,1.0,1.0,1.0,3.0,0.0,1.0,2.0,3.0,1.0,2.0,2.0,1.0,3.0,1.0,2.0,5.0,3.0,1382587.0,25233.0,52.78,52.78,60.24,60.24,61.46,61.46,61.31,61.31,62.5,62.5
2021-07-01,236309.6,213547.2,153024.0,6795339.0,23666.0,7226.0,30892.0,318.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,3.0,1.0,2.0,2.0,1.0,3.0,1.0,2.0,5.0,1.0,1392196.0,25670.0,34.26,34.26,51.19,51.19,46.88,46.88,44.64,44.64,62.5,62.5

In [132]:
merge_limited = merged.loc[merged['new_total_reg'].isna()==False]

In [133]:
merged.to_csv('../capstone-data/merged_na.csv')
merge_limited.to_csv('../capstone-data/merge_limited.csv')